using System;
using System.Linq;

namespace RapidEnum;

public static class RapidEnumTemplate
{
    public static string GenerateAttributes()
    {
        return """
               // <auto-generated/>

               namespace RapidEnum
               {
                   [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
                   [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                   internal sealed class RapidEnumAttribute : global::System.Attribute
                   {
                   
                   }
                   
                   [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
                   [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                   public sealed class RapidEnumWithTypeAttribute : global::System.Attribute
                   {
                       public global::System.Type Type { get; }
                   
                       public RapidEnumWithTypeAttribute(global::System.Type type)
                       {
                           Type = type;
                       }
                   }
               }
               """;
    }

    public static string Generate(RapidEnumGeneratorContext context)
    {
        return $$"""
                  // <auto-generated />

                  {{(!string.IsNullOrEmpty(context.NameSpace) ?
                      $"namespace {context.NameSpace} \n{{" :
                      "")}}
                      
                    {{context.Accessibility}} static partial class {{context.ClassName}}
                    {
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static string ToStringFast(this {{context.EnumFullName}} value)
                        {
                            return value switch
                            {
                                {{
                                    string.Join("\n              ", (context.EnumNames ?? []).Select(x => $"global::{x} => nameof(global::{x}),"))
                                }}
                                _ => value.ToString()
                            };
                        }
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static bool IsDefined({{context.EnumFullName}} value)
                        {
                            return value switch
                            {
                                {{
                                    string.Join("\n              ", (context.EnumNames ?? []).Select(x => $"global::{x} => true,"))
                                }}
                                _ => false,
                            };
                        }
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static bool IsDefined(string name)
                        {
                            return name switch
                            {
                                {{
                                    string.Join("\n              ", (context.EnumNames ?? []).Select(x => $"nameof(global::{x}) => true,"))
                                }}
                                _ => false,
                            };
                        }
                        
                        private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<{{context.EnumFullName}}> CacheValues = new global::System.Collections.ObjectModel.ReadOnlyCollection<{{context.EnumFullName}}>(new[]
                        {
                            {{
                                string.Join("\n          ", (context.EnumNames ?? []).Select(x => $"global::{x},"))
                            }}
                        });
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static global::System.Collections.Generic.IReadOnlyList<{{context.EnumFullName}}> GetValues() => CacheValues;
                    
                        private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<string> CacheNames = new global::System.Collections.ObjectModel.ReadOnlyCollection<string>(new[]
                        {
                            {{
                                string.Join("\n          ", (context.EnumNames ?? []).Select(x => $"nameof(global::{x}),"))
                            }}
                        });
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static global::System.Collections.Generic.IReadOnlyList<string> GetNames() => CacheNames;
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static string GetName({{context.EnumFullName}} value)
                        {
                            return value.ToStringFast();
                        }
                        
                        private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<Member> CacheMembers =  new global::System.Collections.ObjectModel.ReadOnlyCollection<Member>(new[]
                        {
                            {{
                                string.Join("\n          ", (context.EnumNames ?? []).Select(x => $"new Member(nameof(global::{x}), global::{x}),"))
                            }}
                        });
                      
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static global::System.Collections.Generic.IReadOnlyList<Member> GetMembers() => CacheMembers;
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static Member GetMember({{context.EnumFullName}} value)
                        {
                            return value.ToMember();
                        }
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static Member ToMember(this {{context.EnumFullName}} value)
                        {
                            return new Member(ToStringFast(value), value);
                        }
                      
                        public sealed class Member
                        {
                            public string Name { get; }
                            public {{context.EnumFullName}} Value { get; }

                            internal Member(string name, {{context.EnumFullName}} value)
                            {
                                Name = name;
                                Value = value;
                            }
                            
                            public void Deconstruct(out string name, out {{context.EnumFullName}} value)
                            {
                                name = Name;
                                value = Value;
                            }
                        }
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static {{context.EnumFullName}} Parse(string name, bool ignoreCase = false)
                        {
                            if (TryParse(name, out var value, ignoreCase))
                            {
                                return value;
                            }
                            throw new global::System.ArgumentException($"The value '{name}' is not defined in enum '{{context.EnumFullName}}'.");
                        }
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static bool TryParse(
                            string name,
                            out {{context.EnumFullName}} value,
                            bool ignoreCase = false)
                        {
                            return ignoreCase ? TryParseIgnoreCase(name, out value) : TryParse(name, out value);
                        }
                    
                        private static bool TryParseIgnoreCase(
                            string name,
                            out {{context.EnumFullName}} value)
                        {
                            switch (name)
                            {
                                {{
                                    string.Join("\n              ", (context.EnumNames ?? []).Select(x => $"case not null when name.Equals(nameof(global::{x}), global::System.StringComparison.OrdinalIgnoreCase):\n                  value = global::{x};\n                  return true;"))
                                }}
                                case not null when int.TryParse(name, out var val):
                                    value = ({{context.EnumFullName}})val;
                                    return true;
                                default:
                                    value = default;
                                    return false;
                            }
                        }
                    
                        private static bool TryParse(
                            string name,
                            out {{context.EnumFullName}} value)
                        {
                            switch (name)
                            {
                                {{
                                    string.Join("\n              ", (context.EnumNames ?? []).Select(x => $"case nameof(global::{x}):\n                   value = global::{x};\n                  return true;"))
                                }}
                                case not null when int.TryParse(name, out var val):
                                    value = ({{context.EnumFullName}})val;
                                    return true;
                                default:
                                    value = default;
                                    return false;
                            }
                        }
                        
                        private static readonly global::System.Type CacheUnderlyingType = global::System.Enum.GetUnderlyingType(typeof({{context.EnumFullName}}));
                        public static global::System.Type GetUnderlyingType() => CacheUnderlyingType;
                        
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static string GetEnumMemberValue(this {{context.EnumFullName}} value)
                        {
                            return value switch
                            {
                                {{
                                    string.Join("\n              ", (context.EnumNames ?? []).Zip(context.EnumMemberValues ?? [], (x, y) => $"global::{x} => {(y == null ? "null" : "\"" + y + "\"")},"))
                                }}
                                _ => null
                            };
                        }
                    }
                  {{(!string.IsNullOrEmpty(context.NameSpace) ? "}" : "")}}
                  """;
    }
}
