using System;
using System.Linq;
using Microsoft.CodeAnalysis.CSharp;

namespace RapidEnum;

public static class RapidEnumTemplate
{
    private const string SwitchArmIndent = "\n              ";
    private const string ArrayElementIndent = "\n          ";

    public static string GenerateAttributes()
    {
        return """
               // <auto-generated/>

               namespace RapidEnum
               {
                   [global::System.AttributeUsage(global::System.AttributeTargets.Enum)]
                   [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                   internal sealed class RapidEnumAttribute : global::System.Attribute
                   {

                   }

                   [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
                   [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                   public sealed class RapidEnumWithTypeAttribute : global::System.Attribute
                   {
                       public global::System.Type Type { get; }

                       public RapidEnumWithTypeAttribute(global::System.Type type)
                       {
                           Type = type;
                       }
                   }
               }
               """;
    }

    public static string Generate(RapidEnumGeneratorContext context)
    {
        string SwitchArms(Func<EnumMemberInfo, string> selector) => Join(context, SwitchArmIndent, selector);
        string ArrayElements(Func<EnumMemberInfo, string> selector) => Join(context, ArrayElementIndent, selector);

        return $$"""
                  // <auto-generated />
                  
                  #nullable enable annotations

                  {{(!string.IsNullOrEmpty(context.NameSpace) ?
                      $"namespace {context.NameSpace}\n{{" :
                      "")}}

                    {{context.Accessibility}} static partial class {{context.ClassName}}
                    {
                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static string ToStringFast(this {{context.EnumFullName}} value)
                        {
                            return value switch
                            {
                                {{SwitchArms(x => $"global::{x.FullName} => nameof(global::{x.FullName}),")}}
                                _ => value.ToString()
                            };
                        }

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static bool IsDefined({{context.EnumFullName}} value)
                        {
                            return value switch
                            {
                                {{SwitchArms(x => $"global::{x.FullName} => true,")}}
                                _ => false,
                            };
                        }

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static bool IsDefined(string? name)
                        {
                            return name switch
                            {
                                {{SwitchArms(x => $"nameof(global::{x.FullName}) => true,")}}
                                _ => false,
                            };
                        }

                        private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<{{context.EnumFullName}}> CacheValues = new global::System.Collections.ObjectModel.ReadOnlyCollection<{{context.EnumFullName}}>(new[]
                        {
                            {{ArrayElements(x => $"global::{x.FullName},")}}
                        });

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static global::System.Collections.Generic.IReadOnlyList<{{context.EnumFullName}}> GetValues() => CacheValues;

                        private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<string> CacheNames = new global::System.Collections.ObjectModel.ReadOnlyCollection<string>(new[]
                        {
                            {{ArrayElements(x => $"nameof(global::{x.FullName}),")}}
                        });

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static global::System.Collections.Generic.IReadOnlyList<string> GetNames() => CacheNames;

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static string GetName({{context.EnumFullName}} value)
                        {
                            return value.ToStringFast();
                        }

                        private static readonly global::System.Collections.ObjectModel.ReadOnlyCollection<Member> CacheMembers = new global::System.Collections.ObjectModel.ReadOnlyCollection<Member>(new[]
                        {
                            {{ArrayElements(x => $"new Member(nameof(global::{x.FullName}), global::{x.FullName}),")}}
                        });

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static global::System.Collections.Generic.IReadOnlyList<Member> GetMembers() => CacheMembers;

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static Member GetMember({{context.EnumFullName}} value)
                        {
                            return value.ToMember();
                        }

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static Member ToMember(this {{context.EnumFullName}} value)
                        {
                            return new Member(ToStringFast(value), value);
                        }

                        public sealed class Member
                        {
                            public string Name { get; }
                            public {{context.EnumFullName}} Value { get; }

                            internal Member(string name, {{context.EnumFullName}} value)
                            {
                                Name = name;
                                Value = value;
                            }

                            public void Deconstruct(out string name, out {{context.EnumFullName}} value)
                            {
                                name = Name;
                                value = Value;
                            }
                        }

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static {{context.EnumFullName}} Parse(string name, bool ignoreCase = false)
                        {
                            if (TryParse(name, out var value, ignoreCase))
                            {
                                return value;
                            }
                            throw new global::System.ArgumentException($"The value '{name}' is not defined in enum '{{context.EnumFullName}}'.");
                        }

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static bool TryParse(
                            string? name,
                            out {{context.EnumFullName}} value,
                            bool ignoreCase = false)
                        {
                            return ignoreCase ? TryParseIgnoreCase(name, out value) : TryParse(name, out value);
                        }

                        private static bool TryParseIgnoreCase(
                            string? name,
                            out {{context.EnumFullName}} value)
                        {
                            switch (name)
                            {
                                {{SwitchArms(x => $"case not null when name.Equals(nameof(global::{x.FullName}), global::System.StringComparison.OrdinalIgnoreCase):\n                  value = global::{x.FullName};\n                  return true;")}}
                                case not null when {{context.UnderlyingTypeKeyword}}.TryParse(name, out var val):
                                    value = ({{context.EnumFullName}})val;
                                    return true;
                                default:
                                    value = default;
                                    return false;
                            }
                        }

                        private static bool TryParse(
                            string? name,
                            out {{context.EnumFullName}} value)
                        {
                            switch (name)
                            {
                                {{SwitchArms(x => $"case nameof(global::{x.FullName}):\n                  value = global::{x.FullName};\n                  return true;")}}
                                case not null when {{context.UnderlyingTypeKeyword}}.TryParse(name, out var val):
                                    value = ({{context.EnumFullName}})val;
                                    return true;
                                default:
                                    value = default;
                                    return false;
                            }
                        }

                        private static readonly global::System.Type CacheUnderlyingType = global::System.Enum.GetUnderlyingType(typeof({{context.EnumFullName}}));
                        public static global::System.Type GetUnderlyingType() => CacheUnderlyingType;

                        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                        public static string? GetEnumMemberValue(this {{context.EnumFullName}} value)
                        {
                            return value switch
                            {
                                {{SwitchArms(x => $"global::{x.FullName} => {ToLiteral(x.EnumMemberValue)},")}}
                                _ => null
                            };
                        }
                    }
                  {{(!string.IsNullOrEmpty(context.NameSpace) ? "}" : "")}}
                  """;
    }

    private static string Join(
        RapidEnumGeneratorContext context,
        string separator,
        Func<EnumMemberInfo, string> selector)
    {
        return string.Join(separator, (context.EnumMembers ?? []).Select(selector));
    }
    
    private static string ToLiteral(string? value)
    {
        return value == null ? "null" : SymbolDisplay.FormatLiteral(value, quote: true);
    }
}
