<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <RootNamespace>RapidEnum.Sample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RapidEnum.Generators\RapidEnum.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
    </ItemGroup>
</Project>
