name: Release

on:
  workflow_dispatch:

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read version from nuspec
        id: read_version
        run: |
          version=$(xmllint --xpath "string(//package/metadata/version)" RapidEnum.NuGet/RapidEnum.nuspec)
          echo "VERSION=${version}" >> $GITHUB_ENV
      - name: set tag and create release notes
        env: 
          USERNAME: github-actions[bot]
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${USERNAME}"
          git config --global user.email "${EMAIL}"
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dependencies
        run: dotnet restore
        working-directory: .
      - name: Build
        run: dotnet build RapidEnum.sln --no-restore -c Release
      - name: Pack
        run: dotnet pack ./RapidEnum.NuGet/RapidEnum.NuGet.csproj --no-build -c Release -o ./RapidEnum.NuGet
      - name: Publish to NuGet
        working-directory: ./RapidEnum.NuGet
        run: |
          dotnet nuget push "RapidEnum.NuGet/RapidEnum.NuGet.${VERSION}.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json